# Generated by Django 2.1.4 on 2018-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='возраст'),
            preserve_default=False,
        ),
    ]
