# Generated by Django 2.1.7 on 2019-03-02 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20190227_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 19, 12, 33, 574614, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
