# Generated by Django 2.1.7 on 2019-03-02 21:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20190303_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 4, 21, 21, 23, 689748, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
