# Generated by Django 2.1.7 on 2019-03-03 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20190303_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='site',
            new_name='vk_url',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 10, 11, 51, 252660, tzinfo=utc), verbose_name='activation key expires'),
        ),
    ]
