# Generated by Django 2.1.7 on 2019-03-03 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20190303_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='vk_url',
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_page',
            field=models.CharField(blank=True, max_length=128, verbose_name='VK URL'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 11, 28, 20, 741834, tzinfo=utc), verbose_name='activation key expires'),
        ),
    ]
