# Generated by Django 2.1.7 on 2019-03-06 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20190303_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 8, 21, 4, 42, 318071, tzinfo=utc), verbose_name='activation key expires'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='vk_page',
            field=models.CharField(blank=True, max_length=128, verbose_name='VK page'),
        ),
    ]
