# Generated by Django 2.1.7 on 2019-03-12 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20190307_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 15, 33, 149838, tzinfo=utc), verbose_name='activation key expires'),
        ),
    ]
